# Generated by Django 5.0.2 on 2024-03-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='time_duration',
        ),
    ]
