# Generated by Django 5.0.2 on 2024-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time_duration',
            field=models.IntegerField(null=True),
        ),
    ]
